name: mantichor-agent
description: fetch data from mantichor central
outputs:
  manifest:
    description: portainer json manifest
  message:
    description: status or error message
  status_code:
    description: response status code
  base_image:
    description: docker base image
  bypass_code_scan:
    description: bypass snyk code scan
runs:
  using: docker
  image: 'docker://docker.io/gradity/mantichor-agent:v0.1.6'
  post-entrypoint: '/app'
branding:
  icon: cpu
  color: purple
